name: 'Build Discord Container'

on:
  push:
  schedule:
  - cron: 0 8 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: install curl and jq
      run: |
        sudo apt-get update && sudo apt-get install -y curl jq

    - name: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

    - name: Get Discord stable release versions
      run: |
        curl -sSI "https://discordapp.com/api/download?platform=linux&format=deb" | grep -i "location: " | awk "{print $2}" | tr -d "[:space:]" | sed -e "s/.*discord-//g" | sed -e "s/.deb//g" > ${GITHUB_WORKSPACE}/discord-stable-version
    
    - name: Get Discord Canary release version    
      run: |
        curl -sSI "https://discordapp.com/api/download/ptb?platform=linux&format=deb" | grep -i "location: " | awk "{print $2}" | tr -d "[:space:]" | sed -e "s/.*discord-//g" | sed -e "s/.deb//g" > ${GITHUB_WORKSPACE}/discord-canary-version

    - name: Build the latest stable Discord release
      run: |
        docker build --build-arg DOWNLOAD_LINK="https://discordapp.com/api/download?platform=linux&format=deb" -t keyglitch/discord:stable . && \
        docker tag keyglitch/discord:stable keyglitch/discord:stable-$(cat ${GITHUB_WORKSPACE}/discord-stable-version) && \
        docker push keyglitch/discord:stable && \
        docker push keyglitch/discord:stable-$(cat ${GITHUB_WORKSPACE}/discord-stable-version)

    - name: Build the latest canary Discord release
      run: |
        docker build --build-arg DOWNLOAD_LINK="https://discordapp.com/api/download/ptb?platform=linux&format=deb" -t keyglitch/discord:canary . && \
        docker tag keyglitch/discord:canary keyglitch/discord:canary-$(cat ${GITHUB_WORKSPACE}/discord-canary-version) && \
        docker push keyglitch/discord:canary && \
        docker push keyglitch/discord:canary-$(cat ${GITHUB_WORKSPACE}/discord-canary-version)

